### ISSUE TITLE
link lines misplaced with parent padding

### ISSUE THREAD

**Issue by Nanyx** [andrico1234/beautiful-skill-tree#33]
It seams that the position of the lines between two nodes goes off the chart when any upper div uses padding or css library like Bootstrap (tested with v4). It seams that the css of those line use `position: absolute` which might be the problem with computed values...

In any case, keep up the good work !

**Comment by andrico1234** [comment]
Thanks for this!

This is a struggle I've been dealing when creating this package. If you have any suggestions I'd love to hear them. It's what's stopping me from implementing collapsable trees, which is the last feature in my in my V1 checklist. 

One of the biggest issues is that each line (or edge) is position absolute to the window, because I calculate the positions of the nodes using the getClientBoundingRect() method. 

This is less of an issue on the straight edges because it's easy to calculate their positions on a relative basis, because I don't need to worry about their Y positions. It's a lot more difficult to do so for the angled edges.

**Comment by andrico1234** [comment]
@Nanyx 

Thanks for bringing this to light. It was an issue I've known about since creating this package, but have always put off fixing. I've tried in the past to fix it, but the solution has always eluded me. The fact that people are using my package and care about this problem made me give it another shot. 

Which I hope to have fixed in this MR. 

Thanks for raising this ticket, it means a lot to me! :)

**Comment by andrico1234** [comment]
It's been released under version 0.11.9. Please let me know if the fix works for you!

**Comment by Nanyx** [comment]
Give it another go and the fix work just fine ! Great work
