### ISSUE TITLE
Style error when too many children

### ISSUE THREAD

**Issue by gaoryrt** [andrico1234/beautiful-skill-tree#68]
![image](https://user-images.githubusercontent.com/5306513/76067130-d54ed500-5fc9-11ea-8cca-a40df44b8558.png)

https://github.com/andrico1234/beautiful-skill-tree/blob/9cae08c115982f398257a826137e8edb70bb399b/src/components/ui/MiddleAngledLine.tsx#L56

`translateX(-105%)` should be `translateX(calc(4px - 100%))`

**Comment by andrico1234** [comment]
Interesting! Thanks for bringing this up! does `translate(-105%)` work for all use cases, or just your specific width?

It looks like this issue is the same as this one: https://github.com/andrico1234/beautiful-skill-tree/issues/62

Regardless, I'll see what I can come up with after doing some digging

Also, I like the look of this skill tree! Can't wait to see it when it's done.

**Comment by gaoryrt** [comment]
Seems the extra percents in `translate(-105%)` is made for adjusting the horizontal line, but why `5%` instead of `3%`?

I think I can reproduce this error in any case, the more children a node have, the larger gap it shows.

You can find the repo [here](https://github.com/gaoryrt/skill-tree).

**Comment by andrico1234** [comment]
I think i've found the fix. Instead of manually changing the width, I simply flip the element over using `scale(-1)` and add a `translateX(-3px)` to offset the center of the vertical line it connects to. 

This works for nodes with long widths. 

I'll see if this fixes the issue you're having when there are lots of children.

**Comment by andrico1234** [comment]
It looks like this change also fixes your tree!

I copied the structure within the test app!

![image](https://user-images.githubusercontent.com/17087167/76192277-54febe80-61d9-11ea-9c08-b9b1f272cb49.png)

**Comment by andrico1234** [comment]
Fixed in: https://github.com/andrico1234/beautiful-skill-tree/pull/69

**Comment by andrico1234** [comment]
Released with 1.6.2

**Comment by gaoryrt** [comment]
So efficient, thank you!

**Comment by andrico1234** [comment]
Let me know if your tree makes it live, and I can add it to the showcase 😁
